### ISSUE TITLE
Need to know how to pass geofence

### ISSUE THREAD

**Issue by AnshulJain1985** [Kneckter/SpawnpointClusterTool#2]
Hi

We are trying to see how your algorithm works. Can you help me in setting up the geofence how to pass it and how it is used in your algo.

**Comment by Kneckter** [comment]
Geofences are read from RDM's SQL database by passing the `-geo` flag with the name of the RDM instance that has a geofence in it. Do you use RDM or not know what it is? We don't manually pass the geofence coordinates on the command line.

The geofence is used in a MySQL query that forms a polygon in the `ST_GEOMFROMTEXT` statement of the WHERE clause.

**Comment by AnshulJain1985** [comment]
Thanks for quick reply.
We are not using RDM db. I am not sure what it is. Can you please guide me or provide me sample sql through which I can upload the sample data and do testing on it.

**Comment by Kneckter** [comment]
RDM is a mapping program for Pokemon Go (https://github.com/RealDeviceMap/RealDeviceMap). If you are not starting with that kind of data, this might not be too helpful for you. Mind saying what you are trying to use it for?

If you want to create the part of the DB that this script uses, you can make a blank SQL DB and run the below SQL to make two tables.

```sql
CREATE TABLE IF NOT EXISTS `instance` (
  `name` varchar(30) NOT NULL,
  `type` enum('auto_quest','pokemon_iv') NOT NULL,
  `data` longtext NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `spawnpoint` (
  `id` bigint(15) unsigned NOT NULL,
  `lat` double(18,14) NOT NULL,
  `lon` double(18,14) NOT NULL,
  `updated` int(11) unsigned NOT NULL DEFAULT 0,
  `despawn_sec` smallint(6) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_coords` (`lat`,`lon`),
  KEY `ix_updated` (`updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

The lat/lon of the coordinates are stored in the spawnpoint table. The data in the `instance` table is where the geofence is stored and formated as JSON like this:
```json
{"area":[[{"lon":-73.958177,"lat":40.800628},{"lon":-73.949195,"lat":40.797074},{"lon":-73.972773,"lat":40.764458},{"lon":-73.982061,"lat":40.768169},{"lon":-73.958177,"lat":40.800628}]]}
```

This puts a square around Central Park in NY. Note that there are 5 coordinates because a geofence should end with the same coordinate it started with, so the shape is closed. The "area" can be multiple arrays of coordinate tuples to have multiple geofences in one area.

**Comment by AnshulJain1985** [comment]
Thanks for the details above. I got the understanding that its for Pokemon go while going though the code.
Can I connect you over email?

**Comment by Kneckter** [comment]
That would be ok. You can reach me at Mark.Kasulaitis@gmail.com
