### ISSUE TITLE
Start/end PT values?

### ISSUE THREAD

**Issue by hunch-13** [Kneckter/SpawnpointClusterTool#4]
Could we get a bit more info on what these mean/how to use them? I see it wants a line INT but just unsure exactly how you would use this?  I was thinking it wanted lat/lon but that doesn't seem to be the case.

Reason I ask is no matter what I do the final "jump" is always a huge one and I can manually fix it but wondered if I could use these 2 settings to help but perhaps I'm thinking of this wrong.

**Comment by Kneckter** [comment]
These are advanced options that would mainly be used with the just-sort option because the int is the position in the list. That's hard to see when you let the script find the clusters.

These options won't make the large jump much better because the TSP solver uses the greedy algorithm. That method doesn't care about the return trip

**Comment by hunch-13** [comment]
ah okay, I wasn't sure after reading the docs.  So perhaps could you run it twice, first normally then 2nd time with the sort options?  I just can't seem to avoid 1 large jump at the very end

**Comment by Kneckter** [comment]
Running it twice won't avoid that large jump, that's an issue with the greedy algorithm
