### ISSUE TITLE
System Limit

### ISSUE THREAD

**Issue by Dewpg** [Kneckter/SpawnpointClusterTool#7]
How does the script determine the "system's limits" in reference to Sort functions.  The sort job is finished in seconds(maybe 1 second) yet I cannot add points to particular set of points.  Thank you for the wonderful tools.

**Comment by Kneckter** [comment]
No math or queries are done to determine system limits. The tool just lets your system attempt to sort and if it crashes (due to RAM or processing limitation), it returns an error that your systems limits cannot handle what you're sorting.

I have no idea what you mean with adding points. This tool takes a set of points and sorts them, it doesn't have an option to add points to an existing list.
